name: Security Dependency Scan

on:
  # Run on every push to main
  push:
    branches: [main, master]
  
  # Run on every pull request
  pull_request:
    branches: [main, master]
  
  # Run weekly on Monday at 9 AM UTC
  schedule:
    - cron: '0 9 * * 1'
  
  # Allow manual trigger
  workflow_dispatch:

jobs:
  dependency-scan:
    name: Scan Dependencies for Vulnerabilities
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      
      - name: Run pip-audit (Scan for vulnerabilities)
        run: |
          pip-audit --desc --format json --output audit-report.json
        continue-on-error: true
      
      - name: Run pip-audit (Human-readable report)
        run: |
          pip-audit --desc
        continue-on-error: true
      
      - name: Upload vulnerability report
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: security-scan-report
          path: audit-report.json
          retention-days: 30
      
      - name: Check for critical vulnerabilities
        run: |
          # Fail the build if critical vulnerabilities found
          pip-audit --strict --require-hashes=false
