name: "Secret Scanning"

on:
  push:
    branches: [ "main", "security", "dev*" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    # Run daily at 2:00 AM UTC
    - cron: '0 2 * * *'
  workflow_dispatch:  # Allow manual trigger

jobs:
  secret-scan:
    name: Scan for Exposed Secrets
    runs-on: ubuntu-latest
    permissions:
      contents: read
      security-events: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Full history for comprehensive scanning

    - name: TruffleHog Secret Scan
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        base: ${{ github.event.repository.default_branch }}
        head: HEAD
        extra_args: --only-verified --json

    - name: Gitleaks Secret Scan
      id: gitleaks
      uses: gitleaks/gitleaks-action@v2
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Gitleaks SARIF
      if: always()
      uses: github/codeql-action/upload-sarif@v4
      with:
        sarif_file: results.sarif
        category: "gitleaks"

    - name: Secret Scan Summary
      if: always()
      run: |
        if [ "${{ steps.gitleaks.outcome }}" == "failure" ]; then
          echo "🚨 Secrets detected in repository!"
          echo "Review the Security → Code scanning alerts tab for details."
        else
          echo "✅ No secrets detected"
        fi
